import jsPDF from "jspdf";

interface PlanData {
  decedentName?: string;
  step1?: any;
  step2?: any;
  step3?: any;
  step4?: any;
  step5?: any;
  step6?: any;
  step7?: any;
  step8?: any;
}

export const generateAfterLifePlanPDF = (formData: PlanData, decedentName: string) => {
  const pdf = new jsPDF();
  let yPos = 20;
  const pageWidth = pdf.internal.pageSize.width;
  const pageHeight = pdf.internal.pageSize.height;
  const margin = 21.6; // 0.75 inches
  const maxWidth = pageWidth - 2 * margin;
  const lineHeight = 1.15;
  let pageNumber = 1;

  // Helper function to add header
  const addHeader = (sectionName?: string) => {
    const headerY = 10;
    pdf.setFontSize(10);
    pdf.setFont("times", "normal");
    pdf.setTextColor(100, 100, 100);
    const headerText = sectionName 
      ? `Everlasting Funeral Advisors – After-Life Action Plan | ${sectionName}`
      : "Everlasting Funeral Advisors – After-Life Action Plan";
    pdf.text(headerText, pageWidth / 2, headerY, { align: "center" });
  };

  // Helper function to add footer
  const addFooter = () => {
    const footerY = pageHeight - 10;
    pdf.setFontSize(9);
    pdf.setFont("times", "normal");
    pdf.setTextColor(100, 100, 100);
    pdf.text(
      "Generated by Everlasting Funeral Advisors | everlastingfuneraladvisors.com",
      pageWidth / 2,
      footerY,
      { align: "center" }
    );
    pdf.text(String(pageNumber), pageWidth - margin, footerY, { align: "right" });
    
    // Add (Full Legal Name) placeholder at bottom left
    pdf.setFontSize(8);
    pdf.text("(Full Legal Name)", margin, footerY);
    pageNumber++;
  };

  // Helper function to add a new page if needed
  const checkPageBreak = (additionalSpace: number = 15, sectionName?: string) => {
    if (yPos + additionalSpace > pageHeight - 25) {
      addFooter();
      pdf.addPage();
      if (sectionName) addHeader(sectionName);
      yPos = sectionName ? 25 : 20;
      return true;
    }
    return false;
  };

  // Helper function to add wrapped text
  const addWrappedText = (text: string, fontSize: number = 12, isBold: boolean = false) => {
    pdf.setFontSize(fontSize);
    pdf.setFont("times", isBold ? "bold" : "normal");
    pdf.setTextColor(0, 0, 0);
    const lines = pdf.splitTextToSize(text, maxWidth);
    lines.forEach((line: string) => {
      checkPageBreak();
      pdf.text(line, margin, yPos);
      yPos += fontSize * 0.5 * lineHeight;
    });
  };

  // Helper function to add section divider
  const addSectionDivider = () => {
    pdf.setDrawColor(200, 200, 200);
    pdf.setLineWidth(0.5);
    pdf.line(margin, yPos, pageWidth - margin, yPos);
    yPos += 5;
  };

  // Helper function to add field with underline
  const addField = (label: string, value?: string, multiline: boolean = false) => {
    pdf.setFontSize(12);
    pdf.setFont("times", "normal");
    pdf.setTextColor(0, 0, 0);
    pdf.text(label, margin, yPos);
    yPos += 7;
    
    if (value) {
      pdf.setFont("times", "normal");
      if (multiline) {
        addWrappedText(value, 12);
      } else {
        pdf.text(value, margin + 5, yPos);
        yPos += 7;
      }
    } else {
      // Add underline for blank field
      pdf.setDrawColor(204, 204, 204);
      pdf.setLineWidth(0.3);
      const fieldWidth = maxWidth * 0.9;
      pdf.line(margin + 5, yPos, margin + 5 + fieldWidth, yPos);
      yPos += 10;
    }
  };

  // Cover Page
  pdf.setTextColor(0, 0, 0);
  yPos = pageHeight / 2 - 40;
  
  // Title
  pdf.setFontSize(20);
  pdf.setFont("times", "bold");
  pdf.text("After-Life Action Plan", pageWidth / 2, yPos, { align: "center" });
  yPos += 15;
  
  // Add horizontal line under title
  pdf.setDrawColor(150, 150, 150);
  pdf.setLineWidth(0.5);
  pdf.line(margin + 20, yPos, pageWidth - margin - 20, yPos);
  yPos += 20;
  
  // Prepared for
  pdf.setFontSize(12);
  pdf.setFont("times", "normal");
  pdf.text("Prepared for: ", pageWidth / 2 - 50, yPos);
  pdf.setDrawColor(204, 204, 204);
  pdf.setLineWidth(0.3);
  pdf.line(pageWidth / 2 - 10, yPos + 2, pageWidth / 2 + 70, yPos + 2);
  yPos += 15;
  
  // Date Prepared
  pdf.text("Date Prepared: ", pageWidth / 2 - 50, yPos);
  pdf.line(pageWidth / 2 - 10, yPos + 2, pageWidth / 2 + 70, yPos + 2);
  yPos += 25;
  
  // Tagline
  pdf.setFontSize(11);
  pdf.setFont("times", "italic");
  pdf.setTextColor(80, 80, 80);
  const tagline = "Provided by Everlasting Funeral Advisors – Bringing clarity and peace of mind to every family.";
  const taglineLines = pdf.splitTextToSize(tagline, maxWidth - 40);
  taglineLines.forEach((line: string) => {
    pdf.text(line, pageWidth / 2, yPos, { align: "center" });
    yPos += 8;
  });
  
  addFooter();

  // Step 1: Immediate Needs
  pdf.addPage();
  addHeader("IMMEDIATE NEEDS");
  yPos = 30;
  
  pdf.setFontSize(16);
  pdf.setFont("times", "bold");
  pdf.setTextColor(51, 51, 51); // Dark gray #333333
  pdf.text("IMMEDIATE NEEDS (First 48 Hours)", margin, yPos);
  yPos += 10;
  addSectionDivider();
  
  if (formData.step1) {
    const step1 = formData.step1;
    
    pdf.setFontSize(12);
    pdf.setTextColor(0, 0, 0);
    pdf.setFont("times", "bold");
    pdf.text(`${step1.funeralHomeContacted ? "☑" : "☐"} Contact funeral home`, margin, yPos);
    yPos += 7;
    if (step1.funeralHomeName) {
      pdf.setFontSize(12);
      pdf.setFont("times", "normal");
      pdf.text(`   Name: ${step1.funeralHomeName}`, margin + 5, yPos);
      yPos += 6;
    }
    if (step1.funeralHomePhone) {
      pdf.text(`   Phone: ${step1.funeralHomePhone}`, margin + 5, yPos);
      yPos += 6;
    }
    yPos += 5;
    
    pdf.setFont("times", "bold");
    pdf.text(`${step1.residenceSecured ? "☑" : "☐"} Secure residence`, margin, yPos);
    yPos += 7;
    if (step1.residenceNotes) {
      pdf.setFont("times", "normal");
      pdf.text(`   Notes: ${step1.residenceNotes}`, margin + 5, yPos);
      yPos += 6;
    }
    yPos += 5;
    
    pdf.setFont("times", "bold");
    pdf.text(`${step1.familyNotified ? "☑" : "☐"} Notify immediate family`, margin, yPos);
    yPos += 7;
    if (step1.familyContacts) {
      pdf.setFont("times", "normal");
      pdf.text(`   Contacts: ${step1.familyContacts}`, margin + 5, yPos);
      yPos += 6;
    }
    yPos += 5;
    
    if (step1.otherUrgent) {
      pdf.setFont("times", "bold");
      pdf.text("Other urgent items:", margin, yPos);
      yPos += 7;
      pdf.setFont("times", "normal");
      addWrappedText(step1.otherUrgent);
    }
  }
  
  addFooter();

  // Step 2: Official Notifications
  pdf.addPage();
  addHeader("OFFICIAL NOTIFICATIONS");
  yPos = 30;
  
  pdf.setFontSize(16);
  pdf.setFont("times", "bold");
  pdf.setTextColor(51, 51, 51);
  pdf.text("OFFICIAL NOTIFICATIONS", margin, yPos);
  yPos += 10;
  addSectionDivider();
  
  if (formData.step2) {
    const step2 = formData.step2;
    pdf.setFontSize(12);
    pdf.setTextColor(0, 0, 0);
    pdf.setFont("times", "bold");
    
    pdf.text(`${step2.ssaDone ? "☑" : "☐"} Social Security Administration`, margin, yPos);
    yPos += 7;
    if (step2.ssaContact || step2.ssaConfirmation) {
      pdf.setFont("times", "normal");
      if (step2.ssaContact) {
        pdf.text(`   Contact: ${step2.ssaContact}`, margin + 5, yPos);
        yPos += 6;
      }
      if (step2.ssaConfirmation) {
        pdf.text(`   Confirmation: ${step2.ssaConfirmation}`, margin + 5, yPos);
        yPos += 6;
      }
    }
    yPos += 5;
    
    pdf.setFont("times", "bold");
    pdf.text(`${step2.employerDone ? "☑" : "☐"} Employer / HR Contact`, margin, yPos);
    yPos += 7;
    if (step2.employerContact) {
      pdf.setFont("times", "normal");
      pdf.text(`   ${step2.employerContact}`, margin + 5, yPos);
      yPos += 6;
    }
    yPos += 5;
    
    pdf.setFont("times", "bold");
    pdf.text(`${step2.insuranceDone ? "☑" : "☐"} Insurance Company`, margin, yPos);
    yPos += 7;
    if (step2.insuranceCompany || step2.insurancePolicy) {
      pdf.setFont("times", "normal");
      if (step2.insuranceCompany) {
        pdf.text(`   Company: ${step2.insuranceCompany}`, margin + 5, yPos);
        yPos += 6;
      }
      if (step2.insurancePolicy) {
        pdf.text(`   Policy: ${step2.insurancePolicy}`, margin + 5, yPos);
        yPos += 6;
      }
    }
    yPos += 5;
    
    pdf.setFont("times", "bold");
    pdf.text(`${step2.bankDone ? "☑" : "☐"} Bank / Account Closing`, margin, yPos);
    yPos += 7;
    if (step2.bankStatus) {
      pdf.setFont("times", "normal");
      pdf.text(`   ${step2.bankStatus}`, margin + 5, yPos);
      yPos += 6;
    }
    yPos += 5;
    
    pdf.setFont("times", "bold");
    pdf.text(`${step2.utilitiesDone ? "☑" : "☐"} Utilities / Subscriptions`, margin, yPos);
    yPos += 7;
    if (step2.utilitiesList) {
      pdf.setFont("times", "normal");
      pdf.text(`   ${step2.utilitiesList}`, margin + 5, yPos);
    }
  }
  
  addFooter();

  // Step 3: Key Documents
  pdf.addPage();
  addHeader("KEY DOCUMENTS & LOCATIONS");
  yPos = 30;
  
  pdf.setFontSize(16);
  pdf.setFont("times", "bold");
  pdf.setTextColor(51, 51, 51);
  pdf.text("KEY DOCUMENTS & LOCATIONS", margin, yPos);
  yPos += 10;
  addSectionDivider();
  
  if (formData.step3) {
    const step3 = formData.step3;
    pdf.setFontSize(12);
    pdf.setTextColor(0, 0, 0);
    pdf.setFont("times", "normal");
    
    addField("Will / Trust Location:", step3.willLocation);
    addField("Living Trust:", step3.trustLocation);
    addField("Deeds / Titles:", step3.deedsLocation);
    addField("Insurance Policy Folder:", step3.insuranceLocation);
    addField("Tax Returns Found In:", step3.taxDocLocation);
    addField("Safe Deposit Box:", step3.safeDepositBox);
  }
  
  addFooter();

  // Step 4: Death Certificates
  pdf.addPage();
  addHeader("DEATH CERTIFICATES");
  yPos = 30;
  
  pdf.setFontSize(16);
  pdf.setFont("times", "bold");
  pdf.setTextColor(51, 51, 51);
  pdf.text("DEATH CERTIFICATES", margin, yPos);
  yPos += 10;
  addSectionDivider();
  
  if (formData.step4) {
    const step4 = formData.step4;
    pdf.setFontSize(12);
    pdf.setTextColor(0, 0, 0);
    pdf.setFont("times", "normal");
    
    addField("Number Ordered:", step4.numberOrdered?.toString());
    
    if (step4.recipients) {
      pdf.setFont("times", "bold");
      pdf.text("Recipients:", margin, yPos);
      yPos += 7;
      pdf.setFont("times", "normal");
      addWrappedText(step4.recipients);
      yPos += 5;
    }
    
    pdf.setFont("times", "bold");
    pdf.text(`${step4.allReceived ? "☑" : "☐"} All certificates received`, margin, yPos);
  }
  
  addFooter();

  // Step 5: Obituary
  pdf.addPage();
  addHeader("OBITUARY & ANNOUNCEMENTS");
  yPos = 30;
  
  pdf.setFontSize(16);
  pdf.setFont("times", "bold");
  pdf.setTextColor(51, 51, 51);
  pdf.text("OBITUARY & ANNOUNCEMENTS", margin, yPos);
  yPos += 10;
  addSectionDivider();
  
  if (formData.step5) {
    const step5 = formData.step5;
    pdf.setFontSize(12);
    pdf.setTextColor(0, 0, 0);
    
    if (step5.obituaryText) {
      pdf.setFont("times", "bold");
      pdf.text("Obituary Text:", margin, yPos);
      yPos += 7;
      pdf.setFont("times", "normal");
      addWrappedText(step5.obituaryText);
      yPos += 8;
    }
    
    addField("Publication(s):", step5.publications, true);
    addField("Online Link:", step5.onlineLink);
  }
  
  addFooter();

  // Step 6: Service Details
  pdf.addPage();
  addHeader("SERVICE & MEMORIAL DETAILS");
  yPos = 30;
  
  pdf.setFontSize(16);
  pdf.setFont("times", "bold");
  pdf.setTextColor(51, 51, 51);
  pdf.text("SERVICE & MEMORIAL DETAILS", margin, yPos);
  yPos += 10;
  addSectionDivider();
  
  if (formData.step6) {
    const step6 = formData.step6;
    pdf.setFontSize(12);
    pdf.setTextColor(0, 0, 0);
    
    addField("Service Type:", step6.serviceType);
    addField("Venue:", step6.venueName);
    addField("Address:", step6.venueAddress);
    
    if (step6.dateTime) {
      addField("Date/Time:", new Date(step6.dateTime).toLocaleString());
    }
    
    if (step6.officiants) {
      pdf.setFont("times", "bold");
      pdf.text("Officiants:", margin, yPos);
      yPos += 7;
      pdf.setFont("times", "normal");
      addWrappedText(step6.officiants);
      yPos += 5;
    }
    
    if (step6.musicReadings) {
      pdf.setFont("times", "bold");
      pdf.text("Music / Readings:", margin, yPos);
      yPos += 7;
      pdf.setFont("times", "normal");
      addWrappedText(step6.musicReadings);
      yPos += 5;
    }
    
    pdf.setFont("times", "bold");
    pdf.text(`${step6.confirmed ? "☑" : "☐"} Confirmed with funeral home`, margin, yPos);
  }
  
  addFooter();

  // Step 7: Finances & Estate
  pdf.addPage();
  addHeader("FINANCES & ESTATE TASKS");
  yPos = 30;
  
  pdf.setFontSize(16);
  pdf.setFont("times", "bold");
  pdf.setTextColor(51, 51, 51);
  pdf.text("FINANCES & ESTATE TASKS", margin, yPos);
  yPos += 10;
  addSectionDivider();
  
  if (formData.step7) {
    const step7 = formData.step7;
    pdf.setFontSize(12);
    pdf.setTextColor(0, 0, 0);
    
    addField("Executor:", step7.executorName);
    addField("Contact:", step7.executorContact);
    addField("Attorney:", step7.attorney);
    
    if (step7.bankAccounts) {
      pdf.setFont("times", "bold");
      pdf.text("Bank Accounts / Debts:", margin, yPos);
      yPos += 7;
      pdf.setFont("times", "normal");
      addWrappedText(step7.bankAccounts);
      yPos += 5;
    }
    
    if (step7.propertyTransfers) {
      pdf.setFont("times", "bold");
      pdf.text("Property Transfers:", margin, yPos);
      yPos += 7;
      pdf.setFont("times", "normal");
      addWrappedText(step7.propertyTransfers);
      yPos += 5;
    }
    
    pdf.setFont("times", "bold");
    pdf.text(`${step7.estateSettled ? "☑" : "☐"} Estate accounts settled`, margin, yPos);
  }
  
  addFooter();

  // Step 8: Digital Accounts
  pdf.addPage();
  addHeader("DIGITAL ACCOUNTS & ACCESS");
  yPos = 30;
  
  pdf.setFontSize(16);
  pdf.setFont("times", "bold");
  pdf.setTextColor(51, 51, 51);
  pdf.text("DIGITAL ACCOUNTS & ACCESS", margin, yPos);
  yPos += 10;
  addSectionDivider();
  
  if (formData.step8) {
    const step8 = formData.step8;
    pdf.setFontSize(12);
    pdf.setTextColor(0, 0, 0);
    
    addField("Primary Email:", step8.primaryEmail);
    
    if (step8.socialMediaAccounts) {
      pdf.setFont("times", "bold");
      pdf.text("Social Media:", margin, yPos);
      yPos += 7;
      pdf.setFont("times", "normal");
      addWrappedText(step8.socialMediaAccounts);
      yPos += 5;
    }
    
    if (step8.streamingServices) {
      pdf.setFont("times", "bold");
      pdf.text("Streaming / Subscriptions:", margin, yPos);
      yPos += 7;
      pdf.setFont("times", "normal");
      addWrappedText(step8.streamingServices);
      yPos += 5;
    }
    
    pdf.setFont("times", "bold");
    pdf.text(`${step8.allClosed ? "☑" : "☐"} All digital accounts closed`, margin, yPos);
  }
  
  addFooter();

  // Save the PDF
  const fileName = `After-Life-Action-Plan-${decedentName?.replace(/\s+/g, "-") || "Prepared"}-${
    new Date().toISOString().split("T")[0]
  }.pdf`;
  pdf.save(fileName);
};
