import jsPDF from "jspdf";
import logoImage from "@/assets/efa-logo.png";

interface PlanData {
  decedentName?: string;
  preparedFor?: string;
  step1?: any;
  step2?: any;
  step3?: any;
  step4?: any;
  step5?: any;
  step6?: any;
  step7?: any;
  step8?: any;
}

export const generateAfterLifePlanPDF = async (formData: PlanData, decedentName: string) => {
  const pdf = new jsPDF();
  let yPos = 20;
  const pageWidth = pdf.internal.pageSize.width;
  const pageHeight = pdf.internal.pageSize.height;
  const margin = 21.6; // 0.75 inches
  const maxWidth = pageWidth - 2 * margin;
  const lineHeight = 1.25;
  let pageNumber = 1;
  const totalPages = 9; // Cover + 8 sections
  
  // Brand colors
  const efaTeal = [21, 122, 110]; // #157A6E
  const efaGray900 = [31, 41, 55]; // #1F2937
  const efaGray400 = [156, 163, 175]; // #9CA3AF
  
  // Prepared for name (sanitized for filename)
  const preparedForName = (formData.preparedFor || decedentName || "Family")
    .trim()
    .replace(/[^a-zA-Z0-9\s-]/g, "")
    .replace(/\s+/g, "-");

  // Load and convert logo to base64
  let logoBase64 = "";
  try {
    const response = await fetch(logoImage);
    const blob = await response.blob();
    logoBase64 = await new Promise<string>((resolve) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(reader.result as string);
      reader.readAsDataURL(blob);
    });
  } catch (error) {
    console.error("Failed to load logo:", error);
  }

  // Helper function to add logo
  const addLogo = (size: "small" | "large" = "small") => {
    if (!logoBase64) return;
    
    try {
      const logoWidth = size === "large" ? 40 : 30;
      const logoHeight = logoWidth; // Square logo
      const logoX = pageWidth - margin - logoWidth;
      const logoY = size === "large" ? 20 : 5;
      
      pdf.addImage(logoBase64, "PNG", logoX, logoY, logoWidth, logoHeight);
    } catch (error) {
      console.error("Failed to add logo to PDF:", error);
    }
  };

  // Helper function to add header
  const addHeader = (sectionName?: string) => {
    const headerY = 10;
    pdf.setFontSize(9);
    pdf.setFont("helvetica", "normal");
    pdf.setTextColor(efaGray900[0], efaGray900[1], efaGray900[2]);
    
    // Left: Brand name and plan title
    const headerText = sectionName 
      ? `Everlasting Funeral Advisors — After-Life Action Plan | ${sectionName}`
      : "Everlasting Funeral Advisors — After-Life Action Plan";
    pdf.text(headerText, margin, headerY);
    
    // Right: Add logo
    addLogo("small");
  };

  // Helper function to add footer
  const addFooter = () => {
    const footerY = pageHeight - 10;
    pdf.setFontSize(8);
    pdf.setFont("helvetica", "normal");
    pdf.setTextColor(efaGray400[0], efaGray400[1], efaGray400[2]);
    
    // Left: Prepared for name
    pdf.text(`(Prepared for: ${formData.preparedFor || decedentName || "Family"})`, margin, footerY);
    
    // Center: Brand footer
    pdf.text(
      "Generated by Everlasting Funeral Advisors | everlastingfuneraladvisors.com",
      pageWidth / 2,
      footerY,
      { align: "center" }
    );
    
    // Right: Page numbers
    pdf.text(`Page ${pageNumber} of ${totalPages}`, pageWidth - margin, footerY, { align: "right" });
    pageNumber++;
  };

  // Helper function to add a new page if needed
  const checkPageBreak = (additionalSpace: number = 15, sectionName?: string) => {
    if (yPos + additionalSpace > pageHeight - 25) {
      addFooter();
      pdf.addPage();
      if (sectionName) addHeader(sectionName);
      yPos = sectionName ? 25 : 20;
      return true;
    }
    return false;
  };

  // Helper function to add wrapped text
  const addWrappedText = (text: string, fontSize: number = 11.5, isBold: boolean = false) => {
    pdf.setFontSize(fontSize);
    pdf.setFont("helvetica", isBold ? "bold" : "normal");
    pdf.setTextColor(efaGray900[0], efaGray900[1], efaGray900[2]);
    const lines = pdf.splitTextToSize(text, maxWidth);
    lines.forEach((line: string) => {
      checkPageBreak();
      pdf.text(line, margin, yPos);
      yPos += fontSize * 0.5 * lineHeight;
    });
  };

  // Helper function to add section divider
  const addSectionDivider = () => {
    pdf.setDrawColor(efaTeal[0], efaTeal[1], efaTeal[2]);
    pdf.setLineWidth(2);
    pdf.line(margin, yPos, pageWidth - margin, yPos);
    yPos += 8;
  };

  // Helper function to add field with underline
  const addField = (label: string, value?: string, multiline: boolean = false) => {
    pdf.setFontSize(11.5);
    pdf.setFont("helvetica", "normal");
    pdf.setTextColor(efaGray900[0], efaGray900[1], efaGray900[2]);
    pdf.text(label, margin, yPos);
    yPos += 7;
    
    if (value) {
      pdf.setFont("helvetica", "normal");
      if (multiline) {
        addWrappedText(value, 11.5);
      } else {
        pdf.text(value, margin + 5, yPos);
        yPos += 7;
      }
    } else {
      // Add underline for blank field
      pdf.setDrawColor(efaGray400[0], efaGray400[1], efaGray400[2]);
      pdf.setLineWidth(0.3);
      const fieldWidth = maxWidth * 0.9;
      pdf.line(margin + 5, yPos, margin + 5 + fieldWidth, yPos);
      yPos += 10;
    }
  };

  // Cover Page
  // Add logo to cover page
  addLogo("large");
  
  pdf.setTextColor(efaGray900[0], efaGray900[1], efaGray900[2]);
  yPos = pageHeight / 2 - 40;
  
  // Title
  pdf.setFontSize(20);
  pdf.setFont("helvetica", "bold");
  pdf.text("AFTER-LIFE ACTION PLAN", pageWidth / 2, yPos, { align: "center" });
  yPos += 15;
  
  // Add horizontal line under title
  pdf.setDrawColor(efaTeal[0], efaTeal[1], efaTeal[2]);
  pdf.setLineWidth(2);
  pdf.line(margin + 20, yPos, pageWidth - margin - 20, yPos);
  yPos += 20;
  
  // Prepared for
  pdf.setFontSize(11.5);
  pdf.setFont("helvetica", "normal");
  pdf.text("Prepared for: ", pageWidth / 2 - 50, yPos);
  pdf.setDrawColor(efaGray400[0], efaGray400[1], efaGray400[2]);
  pdf.setLineWidth(0.3);
  pdf.line(pageWidth / 2 - 10, yPos + 2, pageWidth / 2 + 70, yPos + 2);
  yPos += 15;
  
  // Date Prepared
  pdf.text("Date Prepared: ", pageWidth / 2 - 50, yPos);
  pdf.line(pageWidth / 2 - 10, yPos + 2, pageWidth / 2 + 70, yPos + 2);
  yPos += 25;
  
  // Tagline
  pdf.setFontSize(10.5);
  pdf.setFont("helvetica", "italic");
  pdf.setTextColor(efaGray400[0], efaGray400[1], efaGray400[2]);
  const tagline = "Provided by Everlasting Funeral Advisors — Bringing clarity and peace of mind to every family.";
  const taglineLines = pdf.splitTextToSize(tagline, maxWidth - 40);
  taglineLines.forEach((line: string) => {
    pdf.text(line, pageWidth / 2, yPos, { align: "center" });
    yPos += 8;
  });
  
  addFooter();

  // Step 1: Immediate Needs
  pdf.addPage();
  addHeader("IMMEDIATE NEEDS");
  yPos = 30;
  
  pdf.setFontSize(15);
  pdf.setFont("helvetica", "bold");
  pdf.setTextColor(efaGray900[0], efaGray900[1], efaGray900[2]);
  pdf.text("IMMEDIATE NEEDS (First 48 Hours)", margin, yPos);
  yPos += 10;
  addSectionDivider();
  
  const step1 = formData.step1 || {};
  
  pdf.setFontSize(11.5);
  pdf.setTextColor(efaGray900[0], efaGray900[1], efaGray900[2]);
  pdf.setFont("helvetica", "bold");
  pdf.text(`${step1.funeralHomeContacted ? "☑" : "☐"} Contact funeral home`, margin, yPos);
  yPos += 7;
  
  addField("   Name:", step1.funeralHomeName);
  addField("   Phone:", step1.funeralHomePhone);
  yPos += 5;
  
  pdf.setFont("helvetica", "bold");
  pdf.text(`${step1.residenceSecured ? "☑" : "☐"} Secure residence`, margin, yPos);
  yPos += 7;
  
  addField("   Notes:", step1.residenceNotes);
  yPos += 5;
  
  pdf.setFont("helvetica", "bold");
  pdf.text(`${step1.familyNotified ? "☑" : "☐"} Notify immediate family`, margin, yPos);
  yPos += 7;
  
  addField("   Contacts:", step1.familyContacts);
  yPos += 5;
  
  pdf.setFont("helvetica", "bold");
  pdf.text("Other urgent items:", margin, yPos);
  yPos += 7;
  
  addField("", step1.otherUrgent, true);
  
  addFooter();

  // Step 2: Official Notifications
  pdf.addPage();
  addHeader("OFFICIAL NOTIFICATIONS");
  yPos = 30;
  
  pdf.setFontSize(15);
  pdf.setFont("helvetica", "bold");
  pdf.setTextColor(efaGray900[0], efaGray900[1], efaGray900[2]);
  pdf.text("OFFICIAL NOTIFICATIONS", margin, yPos);
  yPos += 10;
  addSectionDivider();
  
  const step2 = formData.step2 || {};
  pdf.setFontSize(11.5);
  pdf.setTextColor(efaGray900[0], efaGray900[1], efaGray900[2]);
  pdf.setFont("helvetica", "bold");
  
  pdf.text(`${step2.ssaDone ? "☑" : "☐"} Social Security Administration`, margin, yPos);
  yPos += 7;
  
  addField("   Contact:", step2.ssaContact);
  addField("   Confirmation:", step2.ssaConfirmation);
  yPos += 5;
  
  pdf.setFont("helvetica", "bold");
  pdf.text(`${step2.employerDone ? "☑" : "☐"} Employer or HR Contact`, margin, yPos);
  yPos += 7;
  
  addField("   Contact:", step2.employerContact);
  yPos += 5;
  
  pdf.setFont("helvetica", "bold");
  pdf.text(`${step2.insuranceDone ? "☑" : "☐"} Insurance Company`, margin, yPos);
  yPos += 7;
  
  addField("   Company:", step2.insuranceCompany);
  addField("   Policy:", step2.insurancePolicy);
  yPos += 5;
  
  pdf.setFont("helvetica", "bold");
  pdf.text(`${step2.bankDone ? "☑" : "☐"} Bank or Account Closing`, margin, yPos);
  yPos += 7;
  
  addField("   Status:", step2.bankStatus);
  yPos += 5;
  
  pdf.setFont("helvetica", "bold");
  pdf.text(`${step2.utilitiesDone ? "☑" : "☐"} Utilities or Subscriptions`, margin, yPos);
  yPos += 7;
  
  addField("   List:", step2.utilitiesList);
  
  addFooter();

  // Step 3: Key Documents
  pdf.addPage();
  addHeader("KEY DOCUMENTS AND LOCATIONS");
  yPos = 30;
  
  pdf.setFontSize(15);
  pdf.setFont("helvetica", "bold");
  pdf.setTextColor(efaGray900[0], efaGray900[1], efaGray900[2]);
  pdf.text("KEY DOCUMENTS AND LOCATIONS", margin, yPos);
  yPos += 10;
  addSectionDivider();
  
  const step3 = formData.step3 || {};
  pdf.setFontSize(11.5);
  pdf.setTextColor(efaGray900[0], efaGray900[1], efaGray900[2]);
  pdf.setFont("helvetica", "normal");
  
  addField("Will or Trust Location:", step3.willLocation);
  addField("Living Trust:", step3.trustLocation);
  addField("Deeds or Titles:", step3.deedsLocation);
  addField("Insurance Policy Folder:", step3.insuranceLocation);
  addField("Tax Returns Found In:", step3.taxDocLocation);
  addField("Safe Deposit Box:", step3.safeDepositBox);
  
  addFooter();

  // Step 4: Death Certificates
  pdf.addPage();
  addHeader("DEATH CERTIFICATES");
  yPos = 30;
  
  pdf.setFontSize(15);
  pdf.setFont("helvetica", "bold");
  pdf.setTextColor(efaGray900[0], efaGray900[1], efaGray900[2]);
  pdf.text("DEATH CERTIFICATES", margin, yPos);
  yPos += 10;
  addSectionDivider();
  
  const step4 = formData.step4 || {};
  pdf.setFontSize(11.5);
  pdf.setTextColor(efaGray900[0], efaGray900[1], efaGray900[2]);
  pdf.setFont("helvetica", "normal");
  
  addField("Number Ordered:", step4.numberOrdered?.toString());
  
  pdf.setFont("helvetica", "bold");
  pdf.text("Recipients:", margin, yPos);
  yPos += 7;
  
  addField("", step4.recipients, true);
  yPos += 5;
  
  pdf.setFont("helvetica", "bold");
  pdf.text(`${step4.allReceived ? "☑" : "☐"} All certificates received`, margin, yPos);
  
  addFooter();

  // Step 5: Obituary
  pdf.addPage();
  addHeader("OBITUARY AND ANNOUNCEMENTS");
  yPos = 30;
  
  pdf.setFontSize(15);
  pdf.setFont("helvetica", "bold");
  pdf.setTextColor(efaGray900[0], efaGray900[1], efaGray900[2]);
  pdf.text("OBITUARY AND ANNOUNCEMENTS", margin, yPos);
  yPos += 10;
  addSectionDivider();
  
  const step5 = formData.step5 || {};
  pdf.setFontSize(11.5);
  pdf.setTextColor(efaGray900[0], efaGray900[1], efaGray900[2]);
  
  pdf.setFont("helvetica", "bold");
  pdf.text("Obituary Text:", margin, yPos);
  yPos += 7;
  
  addField("", step5.obituaryText, true);
  yPos += 8;
  
  addField("Publication(s):", step5.publications, true);
  addField("Online Link:", step5.onlineLink);
  
  addFooter();

  // Step 6: Service Details
  pdf.addPage();
  addHeader("SERVICE AND MEMORIAL DETAILS");
  yPos = 30;
  
  pdf.setFontSize(15);
  pdf.setFont("helvetica", "bold");
  pdf.setTextColor(efaGray900[0], efaGray900[1], efaGray900[2]);
  pdf.text("SERVICE AND MEMORIAL DETAILS", margin, yPos);
  yPos += 10;
  addSectionDivider();
  
  const step6 = formData.step6 || {};
  pdf.setFontSize(11.5);
  pdf.setTextColor(efaGray900[0], efaGray900[1], efaGray900[2]);
  
  addField("Service Type:", step6.serviceType);
  addField("Venue:", step6.venueName);
  addField("Address:", step6.venueAddress);
  addField("Date/Time:", step6.dateTime ? new Date(step6.dateTime).toLocaleString() : undefined);
  
  pdf.setFont("helvetica", "bold");
  pdf.text("Officiants:", margin, yPos);
  yPos += 7;
  
  addField("", step6.officiants, true);
  yPos += 5;
  
  pdf.setFont("helvetica", "bold");
  pdf.text("Music or Readings:", margin, yPos);
  yPos += 7;
  
  addField("", step6.musicReadings, true);
  yPos += 5;
  
  pdf.setFont("helvetica", "bold");
  pdf.text(`${step6.confirmed ? "☑" : "☐"} Confirmed with funeral home`, margin, yPos);
  
  addFooter();

  // Step 7: Finances and Estate
  pdf.addPage();
  addHeader("FINANCES AND ESTATE TASKS");
  yPos = 30;
  
  pdf.setFontSize(15);
  pdf.setFont("helvetica", "bold");
  pdf.setTextColor(efaGray900[0], efaGray900[1], efaGray900[2]);
  pdf.text("FINANCES AND ESTATE TASKS", margin, yPos);
  yPos += 10;
  addSectionDivider();
  
  const step7 = formData.step7 || {};
  pdf.setFontSize(11.5);
  pdf.setTextColor(efaGray900[0], efaGray900[1], efaGray900[2]);
  
  addField("Executor:", step7.executorName);
  addField("Contact:", step7.executorContact);
  addField("Attorney:", step7.attorney);
  
  pdf.setFont("helvetica", "bold");
  pdf.text("Bank Accounts or Debts:", margin, yPos);
  yPos += 7;
  
  addField("", step7.bankAccounts, true);
  yPos += 5;
  
  pdf.setFont("helvetica", "bold");
  pdf.text("Property Transfers:", margin, yPos);
  yPos += 7;
  
  addField("", step7.propertyTransfers, true);
  yPos += 5;
  
  pdf.setFont("helvetica", "bold");
  pdf.text(`${step7.estateSettled ? "☑" : "☐"} Estate accounts settled`, margin, yPos);
  
  addFooter();

  // Step 8: Digital Accounts
  pdf.addPage();
  addHeader("DIGITAL ACCOUNTS AND ACCESS");
  yPos = 30;
  
  pdf.setFontSize(15);
  pdf.setFont("helvetica", "bold");
  pdf.setTextColor(efaGray900[0], efaGray900[1], efaGray900[2]);
  pdf.text("DIGITAL ACCOUNTS AND ACCESS", margin, yPos);
  yPos += 10;
  addSectionDivider();
  
  const step8 = formData.step8 || {};
  pdf.setFontSize(11.5);
  pdf.setTextColor(efaGray900[0], efaGray900[1], efaGray900[2]);
  
  addField("Primary Email:", step8.primaryEmail);
  
  pdf.setFont("helvetica", "bold");
  pdf.text("Social Media:", margin, yPos);
  yPos += 7;
  
  addField("", step8.socialMediaAccounts, true);
  yPos += 5;
  
  pdf.setFont("helvetica", "bold");
  pdf.text("Streaming or Subscriptions:", margin, yPos);
  yPos += 7;
  
  addField("", step8.streamingServices, true);
  yPos += 5;
  
  pdf.setFont("helvetica", "bold");
  pdf.text(`${step8.allClosed ? "☑" : "☐"} All digital accounts closed`, margin, yPos);
  
  addFooter();

  // Save the PDF
  const fileName = `After-Life-Action-Plan-${preparedForName}-${
    new Date().toISOString().split("T")[0]
  }.pdf`;
  pdf.save(fileName);
};
