import jsPDF from "jspdf";

interface PlanData {
  prepared_by?: string;
  instructions_notes?: string;
  about_me_notes?: string;
  checklist_notes?: string;
  funeral_wishes_notes?: string;
  financial_notes?: string;
  insurance_notes?: string;
  property_notes?: string;
  pets_notes?: string;
  digital_notes?: string;
  legal_notes?: string;
  messages_notes?: string;
  [key: string]: any;
}

export const generateManuallyFillablePDF = (planData: PlanData) => {
  const pdf = new jsPDF();
  let yPosition = 20;
  const pageHeight = pdf.internal.pageSize.height;
  const pageWidth = pdf.internal.pageSize.width;
  const marginLeft = 20;
  const marginRight = 15; // 0.75" for hole punch
  const marginBottom = 25;
  const lineHeight = 6;
  
  // Color palette
  const colors = {
    headerNavy: [26, 46, 68] as [number, number, number],      // #1A2E44
    subheaderTeal: [14, 118, 118] as [number, number, number], // #0E7676
    bodyGray: [51, 51, 51] as [number, number, number],        // #333333
    lightGray: [221, 221, 221] as [number, number, number],    // #DDDDDD
  };
  
  const profile = planData.personal_profile || {};
  const funeral = planData.funeral || {};

  // Helper to add page footer
  const addPageFooter = (pageNum?: number) => {
    pdf.setFontSize(8);
    pdf.setFont("helvetica", "normal");
    pdf.setTextColor(...colors.bodyGray);
    
    const footerText = "Generated by Everlasting Funeral Advisors – My Final Wishes Planner | everlastingfuneraladvisors.com";
    pdf.text(footerText, pageWidth / 2, pageHeight - 12, { align: "center" });
    
    if (pageNum) {
      pdf.setFontSize(9);
      pdf.text(`Page ${pageNum}`, pageWidth / 2, pageHeight - 7, { align: "center" });
    }
  };

  // Helper to add page header
  const addPageHeader = (title: string, helperText?: string) => {
    pdf.setFontSize(18);
    pdf.setFont("helvetica", "bold");
    pdf.setTextColor(...colors.headerNavy);
    pdf.text(title, marginLeft, yPosition);
    yPosition += 10;
    
    if (helperText) {
      pdf.setFontSize(10);
      pdf.setFont("helvetica", "normal");
      pdf.setTextColor(...colors.bodyGray);
      const lines = pdf.splitTextToSize(helperText, pageWidth - marginLeft - marginRight);
      lines.forEach((line: string) => {
        pdf.text(line, marginLeft, yPosition);
        yPosition += lineHeight;
      });
      yPosition += 6;
    }
  };

  // Helper to add section subheader
  const addSubheader = (text: string) => {
    pdf.setFontSize(14);
    pdf.setFont("helvetica", "bold");
    pdf.setTextColor(...colors.subheaderTeal);
    pdf.text(text, marginLeft, yPosition);
    yPosition += 10;
  };

  // Helper to add checkbox option
  const addCheckbox = (label: string, x?: number) => {
    const posX = x || marginLeft;
    const boxSize = 4;
    
    // Draw empty checkbox
    pdf.setDrawColor(...colors.bodyGray);
    pdf.setLineWidth(0.5);
    pdf.rect(posX, yPosition - 3, boxSize, boxSize);
    
    // Add label
    pdf.setFontSize(11);
    pdf.setFont("helvetica", "normal");
    pdf.setTextColor(...colors.bodyGray);
    pdf.text(label, posX + boxSize + 3, yPosition);
  };

  // Helper to add ruled lines for writing
  const addRuledLines = (numLines: number, labelAbove?: string) => {
    if (labelAbove) {
      pdf.setFontSize(11);
      pdf.setFont("helvetica", "bold");
      pdf.setTextColor(...colors.bodyGray);
      pdf.text(labelAbove, marginLeft, yPosition);
      yPosition += 7;
    }
    
    pdf.setDrawColor(...colors.lightGray);
    pdf.setLineWidth(0.5);
    
    for (let i = 0; i < numLines; i++) {
      if (yPosition > pageHeight - marginBottom) break;
      pdf.line(marginLeft, yPosition, pageWidth - marginRight, yPosition);
      yPosition += 9; // ~0.35" spacing
    }
    
    yPosition += 4;
  };

  // Helper to add a labeled field
  const addLabeledField = (label: string) => {
    pdf.setFontSize(11);
    pdf.setFont("helvetica", "normal");
    pdf.setTextColor(...colors.bodyGray);
    
    const labelWidth = pdf.getTextWidth(label);
    pdf.text(label, marginLeft, yPosition);
    
    // Draw line for writing
    pdf.setDrawColor(...colors.lightGray);
    pdf.setLineWidth(0.5);
    pdf.line(marginLeft + labelWidth + 2, yPosition, pageWidth - marginRight, yPosition);
    yPosition += 9;
  };

  // Helper to fill remaining page with ruled lines
  const fillRemainingWithLines = () => {
    pdf.setDrawColor(...colors.lightGray);
    pdf.setLineWidth(0.5);
    
    while (yPosition < pageHeight - marginBottom - 5) {
      pdf.line(marginLeft, yPosition, pageWidth - marginRight, yPosition);
      yPosition += 9;
    }
  };

  // Cover Page
  pdf.setFillColor(...colors.subheaderTeal);
  pdf.rect(0, 0, pageWidth, 8, 'F');
  
  pdf.setFontSize(28);
  pdf.setFont("helvetica", "bold");
  pdf.setTextColor(...colors.headerNavy);
  pdf.text("My Final Wishes", pageWidth / 2, 45, { align: "center" });
  
  pdf.setFontSize(14);
  pdf.setFont("helvetica", "normal");
  pdf.setTextColor(...colors.bodyGray);
  pdf.text("End-of-Life Planning Guide", pageWidth / 2, 58, { align: "center" });
  
  yPosition = 80;
  pdf.setFontSize(12);
  pdf.setFont("helvetica", "normal");
  pdf.text("This form is designed to be filled out by hand", pageWidth / 2, yPosition, { align: "center" });
  yPosition += 8;
  pdf.text("Please use a pen and write clearly", pageWidth / 2, yPosition, { align: "center" });
  
  yPosition = 110;
  addLabeledField("Prepared for (Full Name):");
  addLabeledField("Date Prepared:");
  
  addPageFooter();

  // PAGE 1 - My Funeral & Memorial Wishes
  pdf.addPage();
  yPosition = 20;
  addPageHeader(
    "My Funeral & Memorial Wishes",
    "This section details your specific wishes for your funeral or memorial arrangements."
  );
  
  addSubheader("Disposition of My Remains");
  addCheckbox("Burial", marginLeft);
  addCheckbox("Cremation", marginLeft + 60);
  addCheckbox("Donation to Science", marginLeft + 120);
  yPosition += 10;
  
  addRuledLines(4, "Notes (e.g., specific wishes for ashes, burial location):");
  
  addSubheader("My Memorial Service Preferences");
  addCheckbox("Home Vigil", marginLeft);
  addCheckbox("Celebration of Life", marginLeft + 70);
  yPosition += 8;
  addCheckbox("Religious Ceremony", marginLeft);
  addCheckbox("Other", marginLeft + 70);
  yPosition += 10;
  
  addRuledLines(3, "Preferred Location:");
  addRuledLines(4, "Music / Readings / Speakers:");
  
  addPageFooter(1);

  // PAGE 2 - Service Details
  pdf.addPage();
  yPosition = 20;
  addPageHeader(
    "Service Details & Preferences",
    "Additional details about how you'd like your service to be conducted."
  );
  
  addSubheader("Additional Service Preferences");
  addCheckbox("Open Casket", marginLeft);
  addCheckbox("Visitation/Viewing", marginLeft + 75);
  yPosition += 8;
  addCheckbox("Military Honors", marginLeft);
  addCheckbox("Graveside Service", marginLeft + 75);
  yPosition += 10;
  
  addRuledLines(4, "Flower Preferences:");
  addRuledLines(4, "Memorial Donations (Charity/Organization):");
  addRuledLines(6, "Special Instructions or Personal Touches:");
  
  addPageFooter(2);

  // PAGE 3 - Personal Information
  pdf.addPage();
  yPosition = 20;
  addPageHeader(
    "My Personal Information",
    "Basic information to help family and officials process your arrangements."
  );
  
  addLabeledField("Full Legal Name:");
  addLabeledField("Nicknames (if any):");
  addLabeledField("Date of Birth:");
  addLabeledField("Place of Birth:");
  addLabeledField("Social Security Number:");
  addLabeledField("Current Address:");
  yPosition += 5;
  addLabeledField("Phone:");
  addLabeledField("Email:");
  addLabeledField("Marital Status:");
  addLabeledField("Spouse/Partner Name:");
  addLabeledField("Religion/Faith:");
  
  yPosition += 8;
  addSubheader("Children's Names");
  addRuledLines(6);
  
  addPageFooter(3);

  // PAGE 4 - Key Contacts
  pdf.addPage();
  yPosition = 20;
  addPageHeader(
    "Key Contacts to Notify",
    "List important people who should be contacted when the time comes."
  );
  
  addSubheader("Contact 1");
  addLabeledField("Name:");
  addLabeledField("Relationship:");
  addLabeledField("Phone/Email:");
  
  yPosition += 8;
  addSubheader("Contact 2");
  addLabeledField("Name:");
  addLabeledField("Relationship:");
  addLabeledField("Phone/Email:");
  
  yPosition += 8;
  addSubheader("Contact 3");
  addLabeledField("Name:");
  addLabeledField("Relationship:");
  addLabeledField("Phone/Email:");
  
  yPosition += 8;
  addRuledLines(8, "Additional Contacts:");
  
  addPageFooter(4);

  // PAGE 5 - Financial & Insurance
  pdf.addPage();
  yPosition = 20;
  addPageHeader(
    "Financial & Insurance Information",
    "Important details about your financial accounts and insurance policies."
  );
  
  addSubheader("Bank Accounts");
  addLabeledField("Institution:");
  addLabeledField("Account Type & Number:");
  
  yPosition += 8;
  addSubheader("Insurance Policies");
  addLabeledField("Life Insurance Company:");
  addLabeledField("Policy Number:");
  addLabeledField("Agent Name & Phone:");
  
  yPosition += 8;
  addRuledLines(10, "Additional Financial Information:");
  
  addPageFooter(5);

  // PAGE 6 - Legal Documents
  pdf.addPage();
  yPosition = 20;
  addPageHeader(
    "Legal Documents & Wishes",
    "Location and details of important legal documents."
  );
  
  addSubheader("Important Documents");
  addCheckbox("Will", marginLeft);
  addCheckbox("Trust", marginLeft + 60);
  addCheckbox("Power of Attorney", marginLeft + 120);
  yPosition += 8;
  addCheckbox("Advance Healthcare Directive", marginLeft);
  addCheckbox("Living Will", marginLeft + 85);
  yPosition += 10;
  
  addRuledLines(4, "Location of Documents:");
  addRuledLines(4, "Attorney Name & Contact:");
  addRuledLines(10, "Special Legal Instructions:");
  
  addPageFooter(6);

  // PAGE 7 - Messages to Loved Ones
  pdf.addPage();
  yPosition = 20;
  addPageHeader(
    "Messages to Loved Ones",
    "Use this space to write personal messages or final thoughts for your loved ones."
  );
  
  addRuledLines(3, "To (Name/Relationship):");
  
  yPosition += 4;
  pdf.setFontSize(11);
  pdf.setFont("helvetica", "bold");
  pdf.setTextColor(...colors.bodyGray);
  pdf.text("Message:", marginLeft, yPosition);
  yPosition += 7;
  
  fillRemainingWithLines();
  
  addPageFooter(7);

  // PAGE 8 - Executor/Planner Contact
  pdf.addPage();
  yPosition = 20;
  addPageHeader(
    "Executor / Planner Contact",
    "Person responsible for carrying out this plan and making arrangements."
  );
  
  addSubheader("Primary Executor");
  addLabeledField("Name:");
  addLabeledField("Phone:");
  addLabeledField("Email:");
  addLabeledField("Address:");
  
  yPosition += 10;
  addSubheader("Backup Contact");
  addLabeledField("Name:");
  addLabeledField("Phone:");
  addLabeledField("Email:");
  
  yPosition += 10;
  addRuledLines(8, "Additional Notes or Instructions:");
  
  addPageFooter(8);

  return pdf;
};