import jsPDF from "jspdf";

interface PlanData {
  prepared_by?: string;
  instructions_notes?: string;
  about_me_notes?: string;
  checklist_notes?: string;
  funeral_wishes_notes?: string;
  financial_notes?: string;
  insurance_notes?: string;
  property_notes?: string;
  pets_notes?: string;
  digital_notes?: string;
  legal_notes?: string;
  messages_notes?: string;
  [key: string]: any;
}

export const generateManuallyFillablePDF = (planData: PlanData) => {
  const pdf = new jsPDF();
  let yPosition = 20;
  const pageHeight = pdf.internal.pageSize.height;
  const pageWidth = pdf.internal.pageSize.width;
  const marginLeft = 20;
  const marginRight = 15; // 0.75" for hole punch
  const marginBottom = 25;
  const lineHeight = 6;
  const tableOfContents: { title: string; page: number }[] = [];
  
  // Color palette
  const colors = {
    headerNavy: [26, 46, 68] as [number, number, number],      // #1A2E44
    subheaderTeal: [14, 118, 118] as [number, number, number], // #0E7676
    bodyGray: [51, 51, 51] as [number, number, number],        // #333333
    lightGray: [221, 221, 221] as [number, number, number],    // #DDDDDD
  };
  
  const profile = planData.personal_profile || {};
  const funeral = planData.funeral || {};

  // Helper to add page footer
  const addPageFooter = (pageNum?: number) => {
    pdf.setFontSize(8);
    pdf.setFont("helvetica", "normal");
    pdf.setTextColor(...colors.bodyGray);
    
    const footerText = "Generated by Everlasting Funeral Advisors – My Final Wishes Planner | everlastingfuneraladvisors.com";
    pdf.text(footerText, pageWidth / 2, pageHeight - 12, { align: "center" });
    
    if (pageNum) {
      pdf.setFontSize(9);
      pdf.text(`Page ${pageNum}`, pageWidth / 2, pageHeight - 7, { align: "center" });
    }
  };

  // Helper to add page header
  const addPageHeader = (title: string, helperText?: string, addToTOC: boolean = true) => {
    // Add to table of contents
    if (addToTOC) {
      const currentPage = pdf.internal.pages.length - 1;
      tableOfContents.push({ title, page: currentPage });
    }
    
    pdf.setFontSize(18);
    pdf.setFont("helvetica", "bold");
    pdf.setTextColor(...colors.headerNavy);
    pdf.text(title, marginLeft, yPosition);
    yPosition += 10;
    
    if (helperText) {
      pdf.setFontSize(10);
      pdf.setFont("helvetica", "normal");
      pdf.setTextColor(...colors.bodyGray);
      const lines = pdf.splitTextToSize(helperText, pageWidth - marginLeft - marginRight);
      lines.forEach((line: string) => {
        pdf.text(line, marginLeft, yPosition);
        yPosition += lineHeight;
      });
      yPosition += 6;
    }
  };

  // Helper to add section subheader
  const addSubheader = (text: string) => {
    pdf.setFontSize(14);
    pdf.setFont("helvetica", "bold");
    pdf.setTextColor(...colors.subheaderTeal);
    pdf.text(text, marginLeft, yPosition);
    yPosition += 10;
  };

  // Helper to add checkbox option
  const addCheckbox = (label: string, x?: number) => {
    const posX = x || marginLeft;
    const boxSize = 4;
    
    // Draw empty checkbox
    pdf.setDrawColor(...colors.bodyGray);
    pdf.setLineWidth(0.5);
    pdf.rect(posX, yPosition - 3, boxSize, boxSize);
    
    // Add label
    pdf.setFontSize(11);
    pdf.setFont("helvetica", "normal");
    pdf.setTextColor(...colors.bodyGray);
    pdf.text(label, posX + boxSize + 3, yPosition);
  };

  // Helper to add ruled lines for writing
  const addRuledLines = (numLines: number, labelAbove?: string) => {
    if (labelAbove) {
      pdf.setFontSize(11);
      pdf.setFont("helvetica", "bold");
      pdf.setTextColor(...colors.bodyGray);
      pdf.text(labelAbove, marginLeft, yPosition);
      yPosition += 7;
    }
    
    pdf.setDrawColor(...colors.lightGray);
    pdf.setLineWidth(0.5);
    
    for (let i = 0; i < numLines; i++) {
      if (yPosition > pageHeight - marginBottom) break;
      pdf.line(marginLeft, yPosition, pageWidth - marginRight, yPosition);
      yPosition += 9; // ~0.35" spacing
    }
    
    yPosition += 4;
  };

  // Helper to add a labeled field
  const addLabeledField = (label: string) => {
    pdf.setFontSize(11);
    pdf.setFont("helvetica", "normal");
    pdf.setTextColor(...colors.bodyGray);
    
    const labelWidth = pdf.getTextWidth(label);
    pdf.text(label, marginLeft, yPosition);
    
    // Draw line for writing
    pdf.setDrawColor(...colors.lightGray);
    pdf.setLineWidth(0.5);
    pdf.line(marginLeft + labelWidth + 2, yPosition, pageWidth - marginRight, yPosition);
    yPosition += 9;
  };

  // Helper to fill remaining page with ruled lines
  const fillRemainingWithLines = () => {
    pdf.setDrawColor(...colors.lightGray);
    pdf.setLineWidth(0.5);
    
    while (yPosition < pageHeight - marginBottom - 5) {
      pdf.line(marginLeft, yPosition, pageWidth - marginRight, yPosition);
      yPosition += 9;
    }
  };

  // Cover Page
  pdf.setFillColor(...colors.subheaderTeal);
  pdf.rect(0, 0, pageWidth, 8, 'F');
  
  pdf.setFontSize(28);
  pdf.setFont("helvetica", "bold");
  pdf.setTextColor(...colors.headerNavy);
  pdf.text("My Final Wishes", pageWidth / 2, 45, { align: "center" });
  
  pdf.setFontSize(14);
  pdf.setFont("helvetica", "normal");
  pdf.setTextColor(...colors.bodyGray);
  pdf.text("End-of-Life Planning Guide", pageWidth / 2, 58, { align: "center" });
  
  yPosition = 80;
  pdf.setFontSize(12);
  pdf.setFont("helvetica", "normal");
  pdf.text("This form is designed to be filled out by hand", pageWidth / 2, yPosition, { align: "center" });
  yPosition += 8;
  pdf.text("Please use a pen and write clearly", pageWidth / 2, yPosition, { align: "center" });
  
  yPosition = 110;
  addLabeledField("Prepared for (Full Name):");
  addLabeledField("Date Prepared:");
  
  addPageFooter();

  // TABLE OF CONTENTS
  pdf.addPage();
  yPosition = 20;
  
  pdf.setFontSize(22);
  pdf.setFont("helvetica", "bold");
  pdf.setTextColor(...colors.headerNavy);
  pdf.text("Table of Contents", pageWidth / 2, yPosition, { align: "center" });
  yPosition += 20;
  
  pdf.setFontSize(11);
  pdf.setFont("helvetica", "normal");
  pdf.setTextColor(...colors.bodyGray);
  
  // We'll fill this in at the end, placeholder for now
  const tocPageNumber = pdf.internal.pages.length - 1;
  
  addPageFooter();

  // PAGE 1 - My Instructions
  pdf.addPage();
  yPosition = 20;
  addPageHeader(
    "My Instructions",
    "Important information about where to find documents, access codes, and special instructions."
  );
  
  addRuledLines(20, "My General Instructions:");
  
  addPageFooter(1);

  // PAGE 2 - Personal Information
  pdf.addPage();
  yPosition = 20;
  addPageHeader(
    "My Personal Information",
    "Basic information to help family and officials process your arrangements."
  );
  
  addLabeledField("Full Legal Name:");
  addLabeledField("Nicknames (if any):");
  addLabeledField("Date of Birth:");
  addLabeledField("Place of Birth:");
  addLabeledField("Social Security Number:");
  addLabeledField("Current Address:");
  yPosition += 5;
  addLabeledField("Phone:");
  addLabeledField("Email:");
  addLabeledField("Marital Status:");
  addLabeledField("Spouse/Partner Name:");
  addLabeledField("Religion/Faith:");
  
  yPosition += 8;
  addSubheader("Children's Names");
  addRuledLines(6);
  
  addPageFooter(2);

  // PAGE 3 - About Me
  pdf.addPage();
  yPosition = 20;
  addPageHeader(
    "About Me",
    "Share your story, values, and what made your life meaningful."
  );
  
  addRuledLines(28, "My Story & Legacy:");
  
  addPageFooter(3);

  // PAGE 4 - Key Contacts
  pdf.addPage();
  yPosition = 20;
  addPageHeader(
    "Key Contacts to Notify",
    "List important people who should be contacted when the time comes."
  );
  
  addSubheader("Contact 1");
  addLabeledField("Name:");
  addLabeledField("Relationship:");
  addLabeledField("Phone/Email:");
  
  yPosition += 8;
  addSubheader("Contact 2");
  addLabeledField("Name:");
  addLabeledField("Relationship:");
  addLabeledField("Phone/Email:");
  
  yPosition += 8;
  addSubheader("Contact 3");
  addLabeledField("Name:");
  addLabeledField("Relationship:");
  addLabeledField("Phone/Email:");
  
  yPosition += 8;
  addRuledLines(8, "Additional Contacts:");
  
  addPageFooter(4);

  // PAGE 5 - Preferred Vendors
  pdf.addPage();
  yPosition = 20;
  addPageHeader(
    "Preferred Vendors",
    "Funeral homes, florists, or other service providers you'd like your family to use."
  );
  
  addSubheader("Vendor 1");
  addLabeledField("Type (e.g., Funeral Home, Florist):");
  addLabeledField("Business Name:");
  addLabeledField("Contact Info:");
  addLabeledField("Notes:");
  
  yPosition += 8;
  addSubheader("Vendor 2");
  addLabeledField("Type:");
  addLabeledField("Business Name:");
  addLabeledField("Contact Info:");
  addLabeledField("Notes:");
  
  yPosition += 8;
  addRuledLines(6, "Additional Vendors:");
  
  addPageFooter(5);

  // PAGE 6 - Checklist
  pdf.addPage();
  yPosition = 20;
  addPageHeader(
    "Checklist",
    "Important tasks you want your loved ones to complete."
  );
  
  pdf.setFontSize(11);
  pdf.setFont("helvetica", "normal");
  pdf.setTextColor(...colors.bodyGray);
  
  for (let i = 1; i <= 20; i++) {
    if (yPosition > pageHeight - marginBottom) break;
    addCheckbox("", marginLeft);
    yPosition += 9;
  }
  
  addPageFooter(6);

  // PAGE 7 - My Funeral & Memorial Wishes
  pdf.addPage();
  yPosition = 20;
  addPageHeader(
    "My Funeral & Memorial Wishes",
    "This section details your specific wishes for your funeral or memorial arrangements."
  );
  
  addSubheader("Disposition of My Remains");
  addCheckbox("Burial", marginLeft);
  addCheckbox("Cremation", marginLeft + 60);
  addCheckbox("Donation to Science", marginLeft + 120);
  yPosition += 10;
  
  addRuledLines(4, "Notes (e.g., specific wishes for ashes, burial location):");
  
  addSubheader("My Memorial Service Preferences");
  addCheckbox("Home Vigil", marginLeft);
  addCheckbox("Celebration of Life", marginLeft + 70);
  yPosition += 8;
  addCheckbox("Religious Ceremony", marginLeft);
  addCheckbox("Other", marginLeft + 70);
  yPosition += 10;
  
  addRuledLines(3, "Preferred Location:");
  addRuledLines(4, "Music / Readings / Speakers:");
  
  addPageFooter(7);

  // PAGE 8 - Financial Life
  pdf.addPage();
  yPosition = 20;
  addPageHeader(
    "Financial Life",
    "Important details about your financial accounts."
  );
  
  addSubheader("Bank Accounts");
  addLabeledField("Institution:");
  addLabeledField("Account Type & Number:");
  
  yPosition += 8;
  addSubheader("Investment Accounts");
  addLabeledField("Institution:");
  addLabeledField("Account Details:");
  
  yPosition += 8;
  addRuledLines(10, "Additional Financial Information:");
  
  addPageFooter(8);

  // PAGE 9 - Insurance
  pdf.addPage();
  yPosition = 20;
  addPageHeader(
    "Insurance",
    "Information about your insurance policies."
  );
  
  addSubheader("Life Insurance Policy 1");
  addLabeledField("Insurance Company:");
  addLabeledField("Policy Number:");
  addLabeledField("Agent Name & Phone:");
  
  yPosition += 8;
  addSubheader("Life Insurance Policy 2");
  addLabeledField("Insurance Company:");
  addLabeledField("Policy Number:");
  addLabeledField("Agent Name & Phone:");
  
  yPosition += 8;
  addRuledLines(8, "Other Insurance (Health, Auto, etc.):");
  
  addPageFooter(9);

  // PAGE 10 - Property
  pdf.addPage();
  yPosition = 20;
  addPageHeader(
    "My Property",
    "Real estate, vehicles, and valuable possessions."
  );
  
  addSubheader("Property I Own");
  addCheckbox("Primary residence", marginLeft);
  addCheckbox("Vacation home", marginLeft + 80);
  yPosition += 8;
  addCheckbox("Investment property", marginLeft);
  addCheckbox("Land or lots", marginLeft + 80);
  yPosition += 8;
  addCheckbox("Vehicles", marginLeft);
  addCheckbox("Boats or RVs", marginLeft + 80);
  yPosition += 8;
  addCheckbox("Business ownership", marginLeft);
  addCheckbox("Jewelry, art, collectibles", marginLeft + 80);
  yPosition += 10;
  
  addRuledLines(12, "Property Details & Location of Deeds/Titles:");
  
  addPageFooter(10);

  // PAGE 11 - Pets
  pdf.addPage();
  yPosition = 20;
  addPageHeader(
    "My Pets",
    "Care instructions and arrangements for your beloved pets."
  );
  
  addRuledLines(28, "Pet Care Instructions:");
  
  addPageFooter(11);

  // PAGE 12 - Digital World
  pdf.addPage();
  yPosition = 20;
  addPageHeader(
    "Digital World",
    "Online accounts, digital assets, and access information."
  );
  
  addSubheader("Digital Assets I Have");
  addCheckbox("Social media accounts", marginLeft);
  addCheckbox("Email accounts", marginLeft + 90);
  yPosition += 8;
  addCheckbox("Cloud storage", marginLeft);
  addCheckbox("Streaming services", marginLeft + 90);
  yPosition += 8;
  addCheckbox("Shopping accounts", marginLeft);
  addCheckbox("Photo sharing sites", marginLeft + 90);
  yPosition += 8;
  addCheckbox("Domain names/websites", marginLeft);
  addCheckbox("Password manager", marginLeft + 90);
  yPosition += 10;
  
  addRuledLines(10, "Account Details & Access Instructions:");
  
  addPageFooter(12);

  // PAGE 13 - Legal Documents
  pdf.addPage();
  yPosition = 20;
  addPageHeader(
    "Legal",
    "Location and details of important legal documents."
  );
  
  addSubheader("Important Documents");
  addCheckbox("Will", marginLeft);
  addCheckbox("Trust", marginLeft + 60);
  addCheckbox("Power of Attorney", marginLeft + 120);
  yPosition += 8;
  addCheckbox("Advance Healthcare Directive", marginLeft);
  addCheckbox("Living Will", marginLeft + 85);
  yPosition += 10;
  
  addRuledLines(4, "Location of Documents:");
  addRuledLines(4, "Attorney Name & Contact:");
  addRuledLines(10, "Special Legal Instructions:");
  
  addPageFooter(13);

  // PAGE 14 - Messages to Loved Ones
  pdf.addPage();
  yPosition = 20;
  addPageHeader(
    "Messages to Loved Ones",
    "Use this space to write personal messages or final thoughts for your loved ones."
  );
  
  addRuledLines(3, "To (Name/Relationship):");
  
  yPosition += 4;
  pdf.setFontSize(11);
  pdf.setFont("helvetica", "bold");
  pdf.setTextColor(...colors.bodyGray);
  pdf.text("Message:", marginLeft, yPosition);
  yPosition += 7;
  
  fillRemainingWithLines();
  
  addPageFooter(14);

  // PAGE 15 - Revisions & Approvals
  pdf.addPage();
  yPosition = 20;
  addPageHeader(
    "Revisions & Approvals",
    "Document updates and approvals to this plan."
  );
  
  addSubheader("Revision 1");
  addLabeledField("Prepared By:");
  addLabeledField("Date:");
  addRuledLines(3, "Signature:");
  
  yPosition += 8;
  addSubheader("Revision 2");
  addLabeledField("Prepared By:");
  addLabeledField("Date:");
  addRuledLines(3, "Signature:");
  
  yPosition += 8;
  addRuledLines(6, "Additional Notes:");
  
  addPageFooter(15);

  // Go back and fill in the Table of Contents
  pdf.setPage(tocPageNumber);
  yPosition = 40;
  
  tableOfContents.forEach((item) => {
    if (yPosition > pageHeight - 40) {
      pdf.addPage();
      yPosition = 20;
    }
    
    pdf.setFontSize(11);
    pdf.setFont("helvetica", "normal");
    pdf.setTextColor(...colors.bodyGray);
    
    const dots = ".".repeat(Math.floor((pageWidth - 80 - pdf.getTextWidth(item.title) - pdf.getTextWidth(String(item.page))) / 2));
    pdf.text(item.title, 30, yPosition);
    pdf.text(dots, 30 + pdf.getTextWidth(item.title) + 2, yPosition);
    pdf.text(String(item.page), pageWidth - 30, yPosition, { align: "right" });
    yPosition += 8;
  });

  return pdf;
};