import jsPDF from "jspdf";

interface PlanData {
  prepared_by?: string;
  instructions_notes?: string;
  about_me_notes?: string;
  checklist_notes?: string;
  funeral_wishes_notes?: string;
  financial_notes?: string;
  insurance_notes?: string;
  property_notes?: string;
  pets_notes?: string;
  digital_notes?: string;
  legal_notes?: string;
  messages_notes?: string;
  [key: string]: any;
}

export const generatePlanPDF = (planData: PlanData) => {
  const pdf = new jsPDF();
  let yPosition = 20;
  const pageHeight = pdf.internal.pageSize.height;
  const marginBottom = 20;
  const lineHeight = 7;

  const checkPageBreak = (additionalSpace: number = 10) => {
    if (yPosition + additionalSpace > pageHeight - marginBottom) {
      pdf.addPage();
      yPosition = 20;
    }
  };

  const addTitle = (title: string) => {
    checkPageBreak(15);
    pdf.setFontSize(16);
    pdf.setFont("helvetica", "bold");
    pdf.text(title, 20, yPosition);
    yPosition += 10;
  };

  const addSection = (heading: string, content?: string) => {
    if (!content) return;
    
    checkPageBreak(20);
    pdf.setFontSize(12);
    pdf.setFont("helvetica", "bold");
    pdf.text(heading, 20, yPosition);
    yPosition += lineHeight;

    pdf.setFontSize(10);
    pdf.setFont("helvetica", "normal");
    const lines = pdf.splitTextToSize(content, 170);
    
    lines.forEach((line: string) => {
      checkPageBreak();
      pdf.text(line, 20, yPosition);
      yPosition += lineHeight;
    });
    yPosition += 5;
  };

  // Cover page
  pdf.setFontSize(24);
  pdf.setFont("helvetica", "bold");
  pdf.text("My Final Wishes", 105, 100, { align: "center" });
  
  pdf.setFontSize(14);
  pdf.setFont("helvetica", "normal");
  pdf.text("End-of-Life Planning Guide", 105, 115, { align: "center" });
  
  if (planData.prepared_by) {
    pdf.setFontSize(12);
    pdf.text(`Prepared by: ${planData.prepared_by}`, 105, 135, { align: "center" });
  }
  
  pdf.setFontSize(10);
  pdf.text(`Generated on: ${new Date().toLocaleDateString()}`, 105, 150, { align: "center" });

  // Add sections
  pdf.addPage();
  yPosition = 20;

  addTitle("📝 Instructions");
  addSection("General Instructions", planData.instructions_notes);

  addTitle("🌟 About Me");
  addSection("About Me", planData.about_me_notes);

  addTitle("✅ Checklist");
  addSection("Checklist Notes", planData.checklist_notes);

  addTitle("🕊️ Funeral Wishes");
  addSection("Funeral Wishes", planData.funeral_wishes_notes);

  addTitle("💰 Financial Life");
  addSection("Financial Information", planData.financial_notes);

  addTitle("🛡️ Insurance");
  addSection("Insurance Information", planData.insurance_notes);

  addTitle("🏠 My Property");
  addSection("Property Information", planData.property_notes);

  addTitle("🐾 My Pets");
  addSection("Pet Care Instructions", planData.pets_notes);

  addTitle("💻 Digital World");
  addSection("Digital Assets & Accounts", planData.digital_notes);

  addTitle("⚖️ Legal");
  addSection("Legal Documents & Information", planData.legal_notes);

  addTitle("❤️ Messages");
  addSection("Messages to Loved Ones", planData.messages_notes);

  // Footer on last page
  checkPageBreak(20);
  pdf.setFontSize(8);
  pdf.setTextColor(128, 128, 128);
  pdf.text("Generated by My Final Wishes - Everlasting Funeral Advisors", 105, pageHeight - 10, { align: "center" });
  pdf.text("https://everlastingfuneraladvisors.com", 105, pageHeight - 5, { align: "center" });

  return pdf;
};
